
#Replace token with a valid token
@token= token 5a9c69d998f7e53b3d9c847459cb60ce06d9d9b2
#
POST http://127.0.0.1:8000/api/v1/bid/ HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "amount":1001,
    "auction_uuid":"4f46145e-be1e-4aca-b7d1-6f308fe4bbd3"
}

###