

GET http://127.0.0.1:8000/api/v1/auction/ HTTP/1.1
Authorization: token b7f672d26b54ead0de20d7e3360ca44d57c5b214
###
POST http://127.0.0.1:8000/api/v1/auction/create HTTP/1.1
Authorization: token b7f672d26b54ead0de20d7e3360ca44d57c5b214
Content-Type: application/json

{
    "title": "WAT",
    "description": "si",
    "starting_bid": 1.00,
    "image_url": "https://www.google.com/search?q=images&tbm=isch&source=iu&ictx=1&vet=1&fir=DH7p1w2o_fIU8M%252CBa_eiczVaD9-zM%252C_%253B2nDXavJs9DoKTM%252CB51x0PBR9KNzvM%252C_%253BsPwUW2x5Z3mupM%252CnBiD9BWYMB87aM%252",
    "currency": "USD"
}